// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomPlayItem: typeof import('./src/components/item/bottomPlayItem.vue')['default']
    Head: typeof import('./src/components/common/head.vue')['default']
    HeadNav: typeof import('./src/components/home/headNav.vue')['default']
    Home: typeof import('./src/components/home/index.vue')['default']
    IconList: typeof import('./src/components/home/iconList.vue')['default']
    List: typeof import('./src/components/item/list.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    Music: typeof import('./src/components/home/musicList/music.vue')['default']
    MusicCom: typeof import('./src/components/home/musicList/musicCom.vue')['default']
    MusicDeatil: typeof import('./src/components/item/musicDeatil.vue')['default']
    MusicList: typeof import('./src/components/home/musicList.vue')['default']
    Result: typeof import('./src/components/search/result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/index.vue')['default']
    Swiper: typeof import('./src/components/home/swiper.vue')['default']
    User: typeof import('./src/components/login/user.vue')['default']
    VanBu: typeof import('vant/es')['Bu']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSearch: typeof import('vant/es')['Search']
    VanSlider: typeof import('vant/es')['Slider']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VantButton: typeof import('vant/es')['tButton']
  }
}
